### ISSUE TITLE
Dropdown list

### ISSUE THREAD

**Issue by mMoliere** [majlis-erc/manuForma#84]
1. The dropdown lists don't display the custom field names at the moment.
2. Is it possible to hide items from the dropdowns in case there is a limit to how many elements of this type can be created?

In this example only one summary may be added. A naive user might decide add a second, resulting in invalid TEI:

![Bildschirmfoto 2023-03-07 um 15 49 14](https://user-images.githubusercontent.com/73166992/223458415-2f799fc0-a334-4d3b-993f-778b79b38bcc.jpg)

3. Can we display the first item in the list instead of the blank item?

**Comment by wsalesky** [comment]
@mMoliere is there anything in the schema to tell me when an item may not be repeated? Or how many times it may be repeated? I do not see anything for the summary. https://github.com/majlis-erc/manuForma/blob/main/forms/schemas/mss-msitem.xml#L281

**Comment by wsalesky** [comment]
@mMoliere the dropdown list naming should be fixed. The issue with repeatable elements remains. There needs to be something in the schema to tell me if an item can be repeated.

**Comment by mMoliere** [comment]
@wsalesky No, the dropdown issues remain. (The generateXForm.xsl I have is Version 1.05 Beta)

**Comment by wsalesky** [comment]
@mMoliere Okay, I will take a look, sounds like I did not get you the most up to date version.

**Comment by wsalesky** [comment]
@mMoliere Is this still an issue on your version?

**Comment by wsalesky** [comment]
I do not have a preference, as long as it is in the schema somewhere. So what ever is easiest for you will probably be fine. If you can mock something up, I can run some tests and see if we can make this work.
